# fly.toml app configuration file generated for simplelibrarysystem-web on 2025-08-21T20:50:08+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'simplelibrarysystem-web'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
